"use client";
import { useRef, useState } from "react";
import PageHeader from "@/components/PageHeader";
const styles=["Clean","Minimal","Luxury","Home / Lifestyle","Natural","Marketplace"];
const backgrounds=["Studio","Bathroom","Living Room","Nature","Luxury","Marketplace White"];
export default function ProductPage(){
 const [file,setFile]=useState<string|null>(null),[style,setStyle]=useState("Clean"),[bg,setBg]=useState("Studio"),[generated,setGenerated]=useState(false); const input=useRef<HTMLInputElement>(null);
 return <><PageHeader eyebrow="COMMERCE / PRODUCT" number="TOOL / 002" title={<>From ordinary.<br/>To ready-to-sell<span className="text-accent">.</span></>} description={<>สร้างภาพสินค้าสำหรับ Shopee, Lazada และ TikTok จากรูปต้นฉบับเพียงภาพเดียว</>}/><div className="page-wrap"><div className="grid gap-0 border border-ink lg:grid-cols-[1.05fr_.95fr]">
  <div className="border-b border-ink p-6 lg:border-b-0 lg:border-r"><div className="mb-5 flex justify-between"><span className="micro">01 / PRODUCT INPUT</span><span className="font-mono text-xs">JPG / PNG / WEBP</span></div><input ref={input} type="file" accept="image/*" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)setFile(URL.createObjectURL(f))}}/><button onClick={()=>input.current?.click()} className="dropzone w-full p-5"><span><span className="mb-4 block text-4xl">＋</span><span className="block">{file?"เปลี่ยนรูปสินค้า":"Upload Product"}</span><span className="mt-2 block text-xs text-muted">รูปเดียวก็เริ่มได้</span></span></button>{file&&<div className="mt-4 flex items-center gap-3 border border-line-soft p-3"><img src={file} className="size-14 object-cover" alt="product"/><div><p className="text-sm">Product image ready</p><p className="micro mt-1 text-muted">BACKGROUND REMOVAL → ENHANCE → COMPOSE</p></div></div>}
  <div className="mt-8 border-t border-line-soft pt-6"><div className="mb-4 flex justify-between"><span className="micro">02 / STYLE</span><span className="text-xs text-muted">SELECT ONE</span></div><div className="grid grid-cols-2 gap-2">{styles.map(x=><button key={x} onClick={()=>setStyle(x)} className={`option ${style===x?"selected":""}`}>{x}</button>)}</div></div>
  <div className="mt-8 border-t border-line-soft pt-6"><div className="mb-4 flex justify-between"><span className="micro">03 / BACKGROUND</span></div><div className="grid grid-cols-2 gap-2">{backgrounds.map(x=><button key={x} onClick={()=>setBg(x)} className={`option ${bg===x?"selected":""}`}>{x}</button>)}</div></div>
  <button disabled={!file} onClick={()=>setGenerated(true)} className="btn-primary mt-8 w-full disabled:opacity-40">{generated?"GENERATED — PREVIEW →":"GENERATE PRODUCT IMAGE  ↗"}</button>
  </div>
  <div className="p-6"><div className="mb-5 flex justify-between"><span className="micro">04 / COMPOSITION PREVIEW</span><span className="micro text-muted">{style} / {bg}</span></div><div className="preview-card grid-paper flex min-h-[560px] items-center justify-center p-10">{file&&generated?<div className="relative max-w-sm"><img src={file} alt="Generated product preview" className="max-h-[480px] w-full object-contain drop-shadow-2xl"/><div className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap border border-ink bg-paper px-4 py-2 font-mono text-[10px] uppercase tracking-wider">AI PRODUCT MOCKUP</div></div>:<div className="max-w-xs text-center"><div className="mb-6 text-6xl font-light">□</div><p className="text-lg font-medium">Your product, re-composed.</p><p className="mt-3 text-sm leading-6 text-muted">ตัวอย่างนี้เป็น UI preview — เมื่อเชื่อม AI แล้วขั้นตอนลบพื้นหลัง ปรับแสง และสร้างฉากจะทำงานอัตโนมัติ</p></div>}</div></div>
 </div><div className="mt-6 grid gap-4 border-t border-ink pt-6 md:grid-cols-4">{["REMOVE BG","LIGHT / DETAIL","GENERATE BG","COMPOSE"].map((x,i)=><div key={x} className="border-t border-ink pt-3"><span className="micro">0{i+1}</span><p className="mt-2 text-sm font-medium">{x}</p></div>)}</div></div></>;
}
