"use client";

import { useRef, useState } from "react";
import PageHeader from "@/components/PageHeader";

type Source = { url: string; name: string; width: number; height: number };
const focus = "focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#ed5127] disabled:cursor-not-allowed disabled:opacity-40";
function Arrow({ down = false }: { down?: boolean }) { return <svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" className={down ? "rotate-90" : ""}><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.5" /></svg>; }

export default function UpscalePage() {
  const [source, setSource] = useState<Source | null>(null), [url, setUrl] = useState(""), [scale, setScale] = useState(2), [result, setResult] = useState<string | null>(null), [resultScale, setResultScale] = useState(2), [view, setView] = useState<"original" | "result">("original"), [busy, setBusy] = useState(false), [loading, setLoading] = useState(false), [dragging, setDragging] = useState(false), [error, setError] = useState(""), [downloading, setDownloading] = useState(false);
  const input = useRef<HTMLInputElement>(null); const selection = useRef(0);

  async function loadImage(imageUrl: string, name: string) {
    const ticket = ++selection.current; setLoading(true); setError(""); setResult(null); setSource(null); setView("original");
    try { const img = new window.Image(); await new Promise<void>((resolve, reject) => { img.onload = () => resolve(); img.onerror = () => reject(new Error("เปิดภาพไม่ได้ กรุณาเลือกไฟล์ใหม่หรือใช้ลิงก์ภาพโดยตรง")); img.src = imageUrl; }); if (ticket !== selection.current) return; if (img.naturalWidth * img.naturalHeight > 16_000_000) throw new Error("กรุณาใช้ภาพขนาดไม่เกิน 16 ล้านพิกเซล"); setSource({ url: imageUrl, name, width: img.naturalWidth, height: img.naturalHeight }); }
    catch (e) { if (ticket === selection.current) setError(e instanceof Error ? e.message : "เปิดภาพไม่ได้"); } finally { if (ticket === selection.current) setLoading(false); }
  }
  function chooseFile(file?: File) { if (!file || busy || loading) return; setError(""); if (!["image/jpeg","image/png","image/webp"].includes(file.type)) return setError("รองรับไฟล์ JPG, PNG และ WebP เท่านั้น"); if (file.size > 4 * 1024 * 1024) return setError("กรุณาเลือกไฟล์ขนาดไม่เกิน 4 MB"); const reader = new FileReader(); reader.onerror = () => setError("อ่านไฟล์ไม่สำเร็จ กรุณาลองอีกครั้ง"); reader.onload = () => void loadImage(String(reader.result), file.name); reader.readAsDataURL(file); }
  async function upscale() { if (!source || busy) return; setBusy(true); setError(""); setResult(null); setView("original"); try { const response = await fetch("/api/upscale", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({ imageUrl:source.url, scale }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "ขยายภาพไม่สำเร็จ กรุณาลองอีกครั้ง"); if (typeof data.result !== "string" || !data.result.startsWith("https://")) throw new Error("ไม่พบลิงก์ภาพผลลัพธ์ กรุณาลองอีกครั้ง"); setResult(data.result); setResultScale(scale); setView("result"); } catch(e) { setError(e instanceof Error ? e.message : "เชื่อมต่อไม่สำเร็จ กรุณาลองอีกครั้ง"); } finally { setBusy(false); } }
  async function download() { if (!result) return; setDownloading(true); setError(""); try { const response = await fetch(result); if (!response.ok) throw new Error(); const blob = await response.blob(), objectUrl = URL.createObjectURL(blob), a = document.createElement("a"); a.href=objectUrl; a.download=`upscaled-${resultScale}x.${blob.type.includes("jpeg")?"jpg":blob.type.includes("webp")?"webp":"png"}`; a.click(); setTimeout(()=>URL.revokeObjectURL(objectUrl),1000); } catch { setError("ดาวน์โหลดอัตโนมัติไม่ได้ กรุณาเปิดภาพผลลัพธ์แล้วบันทึกภาพ"); } finally { setDownloading(false); } }

  return <>
    <PageHeader eyebrow="ENHANCE / RESOLUTION" number="TOOL / 001" title={<>Small image.<br />Bigger possibilities<span className="text-[#ed5127]">.</span></>} description={<>เพิ่มความละเอียดด้วย AI เลือก 2× หรือ 4× แล้วดูผลลัพธ์ใน workspace เดียว</>} />
    <div className="page-wrap">
      <section className="grid border border-[#1d1e1b] lg:grid-cols-[340px_minmax(0,1fr)]">
        <div className="border-b border-[#1d1e1b] p-6 lg:border-b-0 lg:border-r">
          <div className="mb-5 flex items-center justify-between"><h2 className="font-medium">เลือกภาพต้นฉบับ</h2><span className="micro">01 / INPUT</span></div>
          <input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={e=>{chooseFile(e.target.files?.[0]);e.target.value="";}} />
          <button type="button" disabled={busy||loading} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);chooseFile(e.dataTransfer.files[0])}} className={`dropzone w-full p-5 ${dragging?"dragging":""} ${focus}`}><span><span aria-hidden="true" className="mb-4 block text-4xl font-light">＋</span><span className="block">{loading?"กำลังอ่านภาพ…":"ลากภาพมาวาง หรือเลือกไฟล์"}</span><span className="mt-2 block font-mono text-xs text-[#6b6d65]">JPG, PNG, WEBP / MAX. 4 MB</span></span></button>
          <form className="mt-5" onSubmit={e=>{e.preventDefault();try{const parsed=new URL(url);if(parsed.protocol!=="https:")throw new Error();void loadImage(parsed.href,"ภาพจาก URL")}catch{setError("กรุณาใช้ลิงก์ภาพที่ขึ้นต้นด้วย https://")}}}><label htmlFor="image-url" className="mb-2 block text-sm text-[#5b5d55]">หรือใช้ลิงก์ภาพ</label><div className="flex border border-[#bfc0b8]"><input id="image-url" type="url" disabled={busy||loading} placeholder="https://example.com/image.jpg" value={url} onChange={e=>setUrl(e.target.value)} className={`min-w-0 flex-1 bg-transparent px-3 py-3 text-sm ${focus}`} /><button type="submit" disabled={busy||loading||!url} className={`border-l border-[#bfc0b8] px-3 ${focus}`}><Arrow/></button></div></form>
          <div className="mt-7 border-t border-[#d0d1c9] pt-6"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">อัตราขยาย</h2><span className="micro">02 / SCALE</span></div><div className="grid grid-cols-2 gap-3">{[2,4].map(n=><button key={n} type="button" disabled={busy} onClick={()=>setScale(n)} className={`flex items-end justify-between border p-4 ${scale===n?"border-[#1d1e1b] bg-[#1d1e1b] text-white":"border-[#bfc0b8] hover:bg-white"} ${focus}`}><span className="text-4xl font-medium">{n}×</span><span className="font-mono text-xs">{n*100}%</span></button>)}</div><dl className="my-5 flex justify-between text-sm"><dt className="text-[#5b5d55]">ขนาดเป้าหมาย</dt><dd className="font-mono">{source?`${source.width*scale} × ${source.height*scale} px`:"— × — px"}</dd></dl><button disabled={!source||busy||loading} onClick={upscale} className={`btn-primary flex w-full items-center justify-between ${focus}`}><span>{busy?"กำลังขยายภาพ…":"ขยายภาพ"}</span>{busy?<span className="size-5 animate-spin rounded-full border-2 border-black/20 border-t-black"/>:<Arrow/>}</button><p className="mt-3 text-xs leading-5 text-[#686963]">เมื่อเริ่มขยาย ภาพจะถูกส่งไปประมวลผลที่ Replicate</p></div>
        </div>
        <div className="flex min-w-0 flex-col p-6">
          <div className="mb-5 flex flex-wrap items-center justify-between gap-4"><h2 className="micro">03 / PREVIEW</h2><div className="flex border border-[#bfc0b8] p-1">{(["original","result"] as const).map(tab=><button key={tab} disabled={tab==="result"&&!result} onClick={()=>setView(tab)} className={`px-4 py-2 text-sm ${view===tab?"bg-[#1d1e1b] text-white":"hover:bg-white"} ${focus}`}>{tab==="original"?"ต้นฉบับ":"ผลลัพธ์"}</button>)}</div></div>
          <div className="preview-card grid-paper flex flex-1 items-center justify-center p-5" aria-busy={busy}>{source?<img src={view==="result"&&result?result:source.url} alt={view==="result"?"ภาพหลังขยายด้วย AI":"ภาพต้นฉบับ"} className={`max-h-[520px] max-w-full object-contain ${busy?"opacity-40":""}`} onError={()=>setError("แสดงภาพไม่ได้ กรุณาตรวจสอบลิงก์หรือเลือกภาพใหม่")}/>:<div className="py-10 text-center"><div className="mx-auto mb-8 flex size-28 items-center justify-center border border-[#999c90] bg-[#f3f3ee] text-6xl font-light text-[#95988b]">＋</div><p className="text-xl font-medium">A little bigger. A lot clearer.</p><p className="mt-3 text-sm text-[#686963]">เลือกภาพเพื่อเริ่มต้น</p></div>}{busy&&<div className="absolute inset-0 flex items-center justify-center bg-[#f3f3ee]/60"><div className="border border-[#1d1e1b] bg-[#f3f3ee] px-6 py-5 text-center"><p className="micro mb-2">PROCESSING</p><p>AI กำลังประมวลผลภาพ กรุณารอสักครู่</p></div></div>}</div>
          <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><p className="max-w-[320px] truncate text-sm">{source?.name||"ยังไม่ได้เลือกภาพ"}</p><p className="mt-1 font-mono text-xs text-[#686963]">{source?`${source.width} × ${source.height} px${result?` → ${source.width*resultScale} × ${source.height*resultScale} px`:""}`:"READY WHEN YOU ARE"}</p></div><div className="flex items-center gap-4">{result&&<a href={result} target="_blank" rel="noopener noreferrer" className="text-sm underline">เปิดภาพ</a>}<button onClick={download} disabled={!result||downloading} className={`btn-outline flex items-center gap-3 ${focus}`}>{downloading?"กำลังดาวน์โหลด…":"ดาวน์โหลด"}<Arrow down/></button></div></div>
        </div>
      </section>
      {error&&<div role="alert" className="status-line mt-5 text-sm">{error}</div>}
    </div>
  </>;
}
